CNPM_MyPham/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.DTOs;
using Application.Services;
using CNPM_MyPham.Models;
using Microsoft.AspNetCore.Mvc;

namespace CNPM_MyPham.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoginController : Controller
    {
        private readonly NhanVienService NVservice;
        public LoginController(NhanVienService NVservice)
        {
            this.NVservice = NVservice;
            ViewBag.controller = "Login";
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginModelDto lg){
            if(ModelState.IsValid){
                var NV = NVservice.NhanVien_GetByUser(lg.user);
                if(NV == null){
                    ModelState.AddModelError("", "Tài khoản không tồn tại!");
                    return View(lg);
                }

                if(NV.pass != lg.pass){
                    ModelState.AddModelError("", "Mật khẩu sai!");
                    return View(lg);
                }

                NV.pass = "";
                NV.repass = "";
                SessionHelper.SetObjectAsJson(HttpContext.Session, "CurrentUserAdmin", NV);
                return Redirect("/Admin/User/Index");
            }
            return View();
        }
    }
}

CNPM_MyPham/Controllers/LoginController.cs
using Domain.Entities;
using Infrastructure.Persistence;
using CNPM_MyPham.Models;
using Microsoft.AspNetCore.Mvc;
using Domain.Interfaces;
using Application.Services;
using Application.DTOs;
using Application.DTOs.CurrentUserDTO;

namespace CNPM_MyPham.Controllers
{
    public class LoginController : Controller
    {
        private readonly KhachHangService KHservice;
        private readonly LoaiSanPhamService LSPservice;

        public LoginController(KhachHangService KHservice, LoaiSanPhamService LSPservice){
            this.KHservice = KHservice;
            this.LSPservice = LSPservice;
        }

        [HttpGet]
        public IActionResult Index(){
            View_Chung();
            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginModelDto lg){
            if(ModelState.IsValid){
                KhachHangDto kh = KHservice.KhachHang_GetByUser(lg.user);
                if(kh == null){
                    ModelState.AddModelError("", "Tài khoản không tồn tại!");
                    return View(lg);
                }
                else if(kh.pass != lg.pass){
                    ModelState.AddModelError("", "Mật khẩu không đúng!");
                    return View(lg);
                }
                else if (kh.status != 1){
                    ModelState.AddModelError("", "Tài khoản đã bị khóa!");
                    return View(lg);
                }
                CurrentUserDto U = new CurrentUserDto();
                U.KhachHangDto = kh;
                // Không cho hiện mật khẩu khách hàng vào session
                U.KhachHangDto.pass = "";
                U.KhachHangDto.repass = "";
                
                var donhang = SessionHelper.GetObjectFromJson<DonHangDto>(HttpContext.Session, "DonHang");
                if(donhang != null){
                    U.DonHangDto = donhang;
                    donhang = null;
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "DonHang", donhang);
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "CurrentUser", U);
                ViewBag.Message_Login = "Đăng nhập thành công!";
                View_Chung();
                return Redirect("/User/Index");
              //  return View();
            }
            return View();
        }

        public void View_Chung(){
            // Lấy session User hiện hành
            ViewBag.CurrentUser = SessionHelper.GetObjectFromJson<CurrentUserDto>(HttpContext.Session, "CurrentUser");

            // Lấy session Don Hang
            ViewBag.DonHang = SessionHelper.GetObjectFromJson<DonHangDto>(HttpContext.Session, "DonHang");
            
            // Lấy danh sách loại sản phẩm cho danh mục
            ViewBag.Danhmuc = LSPservice.LoaiSanPham_GetAll();
        }
    }
}

CNPM_MyPham/Controllers/RegisterController.cs
using Domain.Entities;
using Infrastructure.Persistence;
using CNPM_MyPham.Models;
using Microsoft.AspNetCore.Mvc;
using Domain.Interfaces;
using Application.Services;
using Application.DTOs;
using Application.DTOs.CurrentUserDTO;
using System;

namespace CNPM_MyPham.Controllers
{
    public class RegisterController : Controller
    {
        private readonly KhachHangService KHservice;

        private readonly LoaiSanPhamService LSPservice;

        public RegisterController(KhachHangService KHservice, LoaiSanPhamService LSPservice){
            this.KHservice = KHservice;
            this.LSPservice = LSPservice;
        }

        [HttpGet]
        public IActionResult Index(){
            View_Chung();
            return View();
        }

        [HttpPost]
        public IActionResult Index(KhachHangDto U){
            if(ModelState.IsValid){
                // checck lớn hơn 18 
                if(DateTime.Now.Year - U.dateborn.Year <= 18 || DateTime.Now.Year - U.dateborn.Year > 80)
                {
                    ModelState.AddModelError("", "Tuổi chỉ được phép từ 18 đến 80!");
                    return View();
                }
                KhachHangDto kh = KHservice.KhachHang_GetByUser(U.user);
                if(kh == null){
                    KHservice.KhachHang_Add(U);
                    CurrentUserDto currentuser = new CurrentUserDto();
                    currentuser.KhachHangDto = U;
                    // Không cho hiện mật khẩu khách hàng vào session
                    currentuser.KhachHangDto.pass = "";
                    currentuser.KhachHangDto.repass = "";
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "CurrentUser", currentuser);
                    View_Chung();
                    U = null;
                    ViewBag.Message_Register = "Đăng kí thành công!";
                     return Redirect("/Login/Index");
                    //return View();
                }
                ModelState.AddModelError("", "Tài khoản đã tồn tại!");
            }
            return View(U);
        }

        public void View_Chung(){
            // Lấy session User hiện hành
            ViewBag.CurrentUser = SessionHelper.GetObjectFromJson<CurrentUserDto>(HttpContext.Session, "CurrentUser");

            // Lấy session Don Hang
            ViewBag.DonHang = SessionHelper.GetObjectFromJson<DonHangDto>(HttpContext.Session, "DonHang");
            
            // Lấy danh sách loại sản phẩm cho danh mục
            ViewBag.Danhmuc = LSPservice.LoaiSanPham_GetAll();
        }
    }
}

CNPM_MyPham/Views/Login/Index.cshtml
@model Application.DTOs.LoginModelDto;
@{
    ViewData["Title"] = "Login";
}

@section Stylesheet{
    <style>
        .field-validation-error {
            color: red
        }

        .validation-summary-errors {
            color: red
        }
    </style>
}

@section Scripts{
    <script src="~/js/Validate-client/jquery-2.2.0.min.js"></script>
    <script src="~/js/Validate-client/jquery.validate.min.js"></script>
    <script src="~/js/Validate-client/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(".nav-menu li").removeClass( "active" );
        $("#page_login").addClass("active");

        Message_Login();
        function Message_Login(){
            @if(ViewBag.Message_Login != null){
                <text>
                $(document).ready(function() {
                    alert("Đăng nhập thành công!");
                });
                </text>
            }
        }
    </script>
}


<!-- Breadcrumb Section Begin -->
<div class="breacrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <a href="#"><i class="fa fa-home"></i> Trang chủ</a>
                    <span>Đăng nhập</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Form Section Begin -->
<!-- Register Section Begin -->
<div class="register-login-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="login-form">
                    <h2>Đăng nhập</h2>
                    <form action="/Login/Index" method="post">
                        <div asp-validation-summary="ModelOnly">
                            <span></span>
                        </div>
                        <div class="group-input">
                            
                            <label asp-for="@Model.user">Tài khoản *</label>                         
                            <input asp-for="@Model.user">
                            <span asp-validation-for="@Model.user"></span>
                        </div>
                        <div class="group-input">
                            <label asp-for="@Model.pass">Mật khẩu *</label>
                            <input asp-for="@Model.pass" type="password">
                            <span asp-validation-for="@Model.pass"></span>
                        </div>
                        <div class="group-input gi-check">
                            <div class="gi-more">
                                @* <label for="save-pass">
                                        Save Password
                                        <input type="checkbox" id="save-pass">
                                        <span class="checkmark"></span>
                                    </label> *@
                                <a href="#" class="forget-pass">Quên mật khẩu</a>
                            </div>
                        </div>
                        <button type="submit" class="site-btn login-btn">Đăng nhập</button>
                    </form>
                    <div class="switch-login">
                        <a asp-controller="Register" asp-action="Index" class="or-login">Tạo tài khoản</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@* <span>@Html.Raw(@ViewData["script"])</span> *@